version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vend-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vend-api
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017
      - MONGODB_DATABASE=vend
      - API_PORT=8080
      - API_HOST=0.0.0.0
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: 