apiVersion: apps/v1
kind: Deployment
metadata:
  name: vend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vend-api
  template:
    metadata:
      labels:
        app: vend-api
    spec:
      containers:
      - name: vend-api
        image: vend-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vend-secrets
              key: database-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: vend-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vend-api
spec:
  selector:
    app: vend-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vend-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.vend.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vend-api
            port:
              number: 80 